Fixes

diff --git a/golosbootstrap.sh.template b/golosbootstrap.sh.template
--- a/golosbootstrap.sh.template
+++ b/golosbootstrap.sh.template
@@ -1,15 +1,24 @@
 #!/bin/bash
 
-GOLOS_REPO="https://github.com/GolosChain/golos"
-
 set -e
-set -x
+#set -x
 
+GOLOS_REPO="https://github.com/GolosChain/golos"
 MODE=build_and_install
+
+# Build Options
+BUILD_OPTIONS="-DCMAKE_BUILD_TYPE=Release"
+
+# Parsing arguments
 if [ ! -z $1 ]; then
 	[ x"build_only" == x"$1" ] && MODE=build_only
 fi
 
+# ###################
+# Checking system
+# ###################
+
+echo "* CHECKING SYSTEM"
 
 # Only works on Ubuntu
 OS=`cat /etc/lsb-release 2>/dev/null| grep DISTRIB_ID | cut -d'=' -f2 | tr '[:upper:]' '[:lower:]'`
@@ -18,17 +27,14 @@ if [[ "x$OS" != "xubuntu" ]]; then
 	exit 1
 fi
 
-# Build Options
-BUILD_OPTIONS="-DCMAKE_BUILD_TYPE=Release -DLOW_MEMORY_NODE=ON -DCLEAR_VOTES=ON"
-
 # Test Physical Memory
 PHYMEM=$(free -g|awk '/^Mem:/{print $2}')
-if (( PHYMEM < 14 )); then
-	echo "WARN: You have Physical Memory < 16Gb, will build LOW_MEMORY_NODE"
-	BUILD_OPTIONS="$BUILD_OPTIONS -DLOW_MEMORY_NODE=ON -DCLEAR_VOTES=ON"
-elif (( PHYMEM < 2 )); then
+if (( PHYMEM < 2 )); then
 	echo "ERROR: You have no enough Physical Memory (min: 2Gb)"
 	exit 1
+elif (( PHYMEM < 14 )); then
+	echo "WARN: You have Physical Memory < 16Gb, will build LOW_MEMORY_NODE"
+	BUILD_OPTIONS="$BUILD_OPTIONS -DLOW_MEMORY_NODE=ON -DCLEAR_VOTES=ON"
 fi
 
 # Get number of processors
@@ -36,7 +42,7 @@ CPUNUM=$(getconf _NPROCESSORS_ONLN)
 
 BASEDIR=`mktemp -d`
 trap 'rm -rf $BASEDIR' EXIT
-pushd $BASEDIR
+pushd $BASEDIR >/dev/null
 
 # Unpack contribute files
 base64 -d <<CONTRIBEOF | tar xz
@@ -49,11 +55,12 @@ CONTRIBEOF
 
 
 # Check if required packages are not installed
+echo "** CHECKING REQUIRED PACKAGES FROM BUILDING"
 PACKAGES_TO_INSTALL=""
 for pkg in git cmake g++ python-dev autotools-dev libicu-dev build-essential libbz2-dev libboost-all-dev libssl-dev libncurses5-dev doxygen libreadline-dev dh-autoreconf build-essential; do
 	PKG_OK=no
 	dpkg-query -W --showformat='${Status}\n' $pkg | grep "install ok installed" > /dev/null && PKG_OK=yes
-	echo Checking for $pkg: $PKG_OK
+	echo " - Checking for $pkg: $PKG_OK"
 	if [ x"no" == x"$PKG_OK" ]; then
 		  PACKAGES_TO_INSTALL="$PACKAGES_TO_INSTALL $pkg"
 	fi
@@ -61,8 +68,8 @@ done
 
 # If found missed packages - install
 if [ x"" != x"$PACKAGES_TO_INSTALL" ]; then
-	sudo apt-get update || :
-	sudo apt-get install -y $PACKAGES_TO_INSTALL
+	sudo apt-get update >> $BASEDIR/log 2>&1 || : 
+	sudo apt-get install -y $PACKAGES_TO_INSTALL >> $BASEDIR/log 2>&1
 fi
 
 
@@ -73,6 +80,8 @@ fi
 # Building Golosnode
 ##################################
 
+echo "* BULDING GOLOS"
+
 # Create folder for installing node
 DEB_PATH=$BASEDIR/package/golos
 GOLOS_PATH=$BASEDIR/package/golos/opt/golos
@@ -80,16 +89,19 @@ mkdir -p $DEB_PATH
 mkdir -p $GOLOS_PATH
 
 # Clone Golos
-git clone $GOLOS_REPO
+echo "** DOWNLOADING SOURCE CODE"
+git clone $GOLOS_REPO >> $BASEDIR/log 2>&1
 cd golos
-git checkout master
-git submodule update --init --recursive
+git checkout master >> $BASEDIR/log 2>&1
+git submodule update --init --recursive >> $BASEDIR/log 2>&1
 
 # Build
-cmake $BUILD_OPTIONS .
-make -j$CPUNUM
+echo "** COMPILING"
+cmake $BUILD_OPTIONS . >> $BASEDIR/log 2>&1
+make -j$CPUNUM >> $BASEDIR/log 2>&1
 
 # Preparing golosnode package
+echo "** PREPARING FILES FOR PACKAGING"
 install -m 0755 programs/golosd/golosd $GOLOS_PATH/
 install -m 0644 programs/golosd/snapshot5392323.json $GOLOS_PATH
 install -m 0755 programs/cli_wallet/cli_wallet $GOLOS_PATH
@@ -109,19 +121,25 @@ sed -i "s/##GOLOS_VERSION##/$GOLOS_VERSION/" $DEB_PATH/DEBIAN/control
 sed -i "s/##UNIXTIME##/$UNIXTIME/" $DEB_PATH/DEBIAN/control
 
 # Make deb package
-fakeroot dpkg-deb --build $DEB_PATH
+echo "** PACKAGING"
+fakeroot dpkg-deb --build $DEB_PATH >> $BASEDIR/log
 
-mv -v $DEB_PATH/../golos.deb /tmp/golos-$GOLOS_VERSION-$UNIXTIME.deb
-
-echo 
-echo "#############################################################"
-echo "DEB package path: /tmp/golos-${GOLOS_VERSION}-${UNIXTIME}.deb"
-echo "#############################################################"
-echo 
+mv $DEB_PATH/../golos.deb /tmp/golos-$GOLOS_VERSION-$UNIXTIME.deb
 
 if [ x"$MODE" == x"build_and_install" ]; then
-	sudo dpkg -i /tmp/golos-$GOLOS_VERSION-$UNIXTIME.deb
+	echo "* INSTALLING"
+	sudo dpkg -i /tmp/golos-$GOLOS_VERSION-$UNIXTIME.deb >> $BASEDIR/log
 fi
 
-popd # basedir
+echo "* DONE"
+echo
+echo "- DEB package path: /tmp/golos-${GOLOS_VERSION}-${UNIXTIME}.deb"
+echo
+echo "-- To run golosd use: systemctl start golosd"
+echo "-- To check golosd use: systemctl status golosd"
+echo "-- To stop golosd use: systemctl stop golosd"
+echo "-- Golos path: /opt/golos"
+echo 
+
+popd > /dev/null # basedir
 
